version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - NODE_ENV=production
      - DB_URL=postgresql://root:dbpass@postgres:5432/app
    ports:
      - 8080:80
    networks:
      - backend
    volumes:
      - ./logs/app:/app/logs

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=app
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - ./_dbdata/pg:/var/lib/postgresql/data

  neo4j:
    image: bitnami/neo4j:latest
    environment:
      - NEO4J_PASSWORD=neo4jpass
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - backend
    volumes:
      - ./_dbdata/neo4j:/data

networks:
  backend:
