version: '3'

services:
  app:
    environment:
      - NODE_ENV=development

  etl:
    build:
      dockerfile: Dockerfile.ETL
      context: .
    environment:
      - MONGO_URL=mongodb://root:mongopass@mongo:27017
      - GPLACES_API_KEY=AIzaSyAPUn2r10zmq_JEauPmsFWINsWk4avl3cc
      - NEO4J_HOST=neo4j://neo4j
      - NEO4J_PORT=7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j
    networks:
      - backend
    volumes:
      - ./logs/etl:/app/logs
