version: '3'

services:
  app:
    container_name: app
    build: .
    environment:
      - PORT
      - MODE
      - DB_URL
    ports:
      - "${PORT}:${PORT}"
    networks:
      - backend
    volumes:
      - ./logs:/app/logs

  studio:
    container_name: studio
    build: .
    command:
      - db:studio
    environment:
      - DB_URL
      - STUDIO_PORT
    ports:
      - "${STUDIO_PORT}:${STUDIO_PORT}"
    networks:
      - backend

  db:
    container_name: db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  backend:

volumes:
  db-data:
