version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - MONGO_URL=mongodb://root:mongopass@mongo:27017
      - NEO4J_HOST=neo4j://neo4j
      - NEO4J_PORT=7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j
    ports:
      - 80:8080
    networks:
      - backend
    volumes:
      - ./logs/app:/app/logs

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopass
    ports:
      - 27017:27017
    networks:
      - backend
    volumes:
      - ./_dbdata/mongo:/data/db

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_procedures_unrestricted=algo.*, apoc.*, gds.*
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - backend
    volumes:
      - ./_dbdata/neo4j:/data
      - ./neo4j_plugins:/plugins

networks:
  backend:
