version: '3'

services:
  app:
    environment:
      - NODE_ENV=development

  etl:
    build:
      dockerfile: Dockerfile.ETL
      context: .
    environment:
      - MONGO_URL=mongodb+srv://root:mongopass@mongo:27017
      - GPLACES_API_KEY=AIzaSyAPUn2r10zmq_JEauPmsFWINsWk4avl3cc
    networks:
      - backend
    volumes:
      - ./logs/etl:/app/logs
