version: '3'

services:
  app:
    container_name: app
    build: .
    environment:
      - PORT=80
      - MODE=dev
      - DB_URL=postgresql://root:dbpass@postgres:5432/app
    ports:
      - 80:80
    networks:
      - backend
    volumes:
      - ./logs:/app/logs

  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=app
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

  neo4j:
    container_name: neo4j
    image: bitnami/neo4j:latest
    environment:
      - NEO4J_PASSWORD=neo4jpass
      - NEO4J_HTTP_PORT_NUMBER=7474
      - NEO4J_HTTPS_PORT_NUMBER=7473
      - NEO4J_BOLT_PORT_NUMBER=7687
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    networks:
      - backend

networks:
  backend:

volumes:
  db-data:
