version: '3'

services:
  app:
    container_name: app
    build: .
    environment:
      - PORT=80
      - MODE=dev
      - DB_URL=postgresql://root:dbpass@db:5432/app
    ports:
      - "80:80"
    networks:
      - backend
    volumes:
      - ./logs:/app/logs

  db:
    container_name: db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=app
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  backend:

volumes:
  db-data:
