version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb+srv://root:mongopass@mongo:27017
    ports:
      - 8080:80
    networks:
      - backend
    volumes:
      - ./logs/app:/app/logs

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopass
    ports:
      - 27017:27017
    networks:
      - backend
    volumes:
      - ./_dbdata/mongo:/data/db

  neo4j:
    image: bitnami/neo4j:latest
    environment:
      - NEO4J_PASSWORD=neo4jpass
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - backend
    volumes:
      - ./_dbdata/neo4j:/data

networks:
  backend:
